kind: Deployment
apiVersion: apps/v1

metadata:
  name: tt-deployment
  labels:
    app: tt

spec:
  replicas: 4
  selector:
    matchLabels:
      app: tt
  template:
    metadata:
      labels:
        app: tt

    spec:
      containers:
        - name: flask-app-cont
          image: mishranishant/flask-app:1.0.2
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: nishant_sql
            - name: MYSQL_PASSWORD
              value: "1430"
            - name: MYSQL_DB
              value: nishant_db

